(define (problem shakey-rooms)
 (:domain shakey)
 (:objects 
 box shakey hand-1 hand-2 room-0
 room-1 obj-1
 room-2 obj-2
 room-3 obj-3
 room-4 obj-4
 room-5 obj-5
 room-6 obj-6
 room-7 obj-7
 room-8 obj-8
 room-9 obj-9
 room-10 obj-10
)
 (:init (at shakey room-0)
 (at box room-0)
 (is-box box)
 (is-shakey shakey)
 (is-hand hand-1)
 (is-hand hand-2)
 (free-hand hand-1)
 (free-hand hand-2)
 (door room-1 room-2) (door room-2 room-1)
 (door room-2 room-3) (door room-3 room-2)
 (door room-3 room-4) (door room-4 room-3)
 (door room-4 room-5) (door room-5 room-4)
 (door room-5 room-6) (door room-6 room-5)
 (door room-6 room-7) (door room-7 room-6)
 (door room-7 room-8) (door room-8 room-7)
 (door room-8 room-9) (door room-9 room-8)
 (door room-9 room-10) (door room-10 room-9)
 (door room-10 room-1) (door room-1 room-10)
 (wide-door room-1 room-0) (wide-door room-0 room-1)
 (wide-door room-2 room-0) (wide-door room-0 room-2)
 (wide-door room-3 room-0) (wide-door room-0 room-3)
 (wide-door room-4 room-0) (wide-door room-0 room-4)
 (wide-door room-5 room-0) (wide-door room-0 room-5)
 (wide-door room-6 room-0) (wide-door room-0 room-6)
 (wide-door room-7 room-0) (wide-door room-0 room-7)
 (wide-door room-8 room-0) (wide-door room-0 room-8)
 (wide-door room-9 room-0) (wide-door room-0 room-9)
 (wide-door room-10 room-0) (wide-door room-0 room-10)
 (switch-in room-1)
 (switch-in room-2)
 (switch-in room-3)
 (switch-in room-4)
 (switch-in room-5)
 (switch-in room-6)
 (switch-in room-7)
 (switch-in room-8)
 (switch-in room-9)
 (switch-in room-10)
 (is-small-obj obj-1) (at obj-1 room-1)
 (is-small-obj obj-2) (at obj-2 room-2)
 (is-small-obj obj-3) (at obj-3 room-3)
 (is-small-obj obj-4) (at obj-4 room-4)
 (is-small-obj obj-5) (at obj-5 room-5)
 (is-small-obj obj-6) (at obj-6 room-6)
 (is-small-obj obj-7) (at obj-7 room-7)
 (is-small-obj obj-8) (at obj-8 room-8)
 (is-small-obj obj-9) (at obj-9 room-9)
 (is-small-obj obj-10) (at obj-10 room-10)
)
 (:goal (and  (at obj-1 room-2)
 (at obj-2 room-3)
 (at obj-3 room-4)
 (at obj-4 room-5)
 (at obj-5 room-6)
 (at obj-6 room-7)
 (at obj-7 room-8)
 (at obj-8 room-9)
 (at obj-9 room-10)
 (at obj-10 room-1)
))
)